version: "3.9"

volumes:
  db:
  bundle:

services:
  db:
    image: postgres:14.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file: app.env
    stdin_open: true
    tty: true
    environment:
      # App database config
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PWD=
      - RAILS_MAX_THREADS=5

  redis:
    image: redis:7.0.11